#!/usr/bin/env python3
"""Regenerates docs/command-reference.md straight from every command's
--help text, so the reference can't drift from the actual flags. Run it
after adding/changing a command:

    python3 scripts/generate_command_reference.py

It walks the real Click command tree (no shelling out, no parsing text
that's already been rendered once) and writes one section per command,
each holding exactly what `meshcorectl <path> --help` prints.
"""

from __future__ import annotations

import sys
from collections.abc import Iterator
from pathlib import Path

import click

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from meshcorectl.cli import cli  # noqa: E402 - path insert above must run first

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "docs" / "command-reference.md"


def iter_commands(
    command: click.Command, ctx: click.Context
) -> Iterator[tuple[click.Context, click.Command]]:
    """Depth-first walk of `command` and, if it's a Group, every
    subcommand, each paired with the Context `--help` needs to render it
    with the right `command_path` (e.g. "meshcorectl get contact")."""
    yield ctx, command
    if isinstance(command, click.Group):
        for name in sorted(command.list_commands(ctx)):
            sub = command.get_command(ctx, name)
            if sub is None:  # pragma: no cover - defensive, Click guarantees this exists
                continue
            sub_ctx = click.Context(sub, info_name=name, parent=ctx)
            yield from iter_commands(sub, sub_ctx)


def build_reference(root: click.Command, prog_name: str) -> str:
    root_ctx = click.Context(root, info_name=prog_name)
    entries = list(iter_commands(root, root_ctx))

    lines = [
        "# meshcorectl command reference",
        "",
        "Generated by `scripts/generate_command_reference.py` from each command's own",
        "`--help` output — do not edit by hand, regenerate it instead.",
        "",
        "## Contents",
        "",
    ]
    for ctx, _command in entries:
        anchor = ctx.command_path.replace(" ", "-")
        lines.append(f"- [`{ctx.command_path}`](#{anchor})")
    lines.append("")

    for ctx, command in entries:
        lines.append(f"## `{ctx.command_path}`")
        lines.append("")
        lines.append("```")
        lines.append(command.get_help(ctx))
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    text = build_reference(cli, "meshcorectl")
    OUTPUT_PATH.write_text(text)
    print(f"wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
